user:
  index:
    clone:
      name: clone
      nav_header: "Bulk Action"
      path: ""
    lock:
      name: lock
      path: ""
    trash:
      name: trash
      path: ""
  not_index:
    show:
      name: show
      nav_header: "View Action"
    edit:
      name: edit
    privileges:
      name: privileges
    preferences:
      name: preferences

role:
  index:
    clone:
      name: clone
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: trash
      path: ""
  not_index:
    assigned:
      name: assigned
      nav_header: "Role Assignment"
    edit:
      name: edit

permission:
  index:
    clone:
      name: clone
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: trash
      path: ""
  not_index:
    assigned:
      name: assigned
      nav_header: "Permission Assignment"
    edit:
      name: edit
  new_user:

project:
  index:
    clone:
      name: clone
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: trash
      path: ""
  not_index:
    assigned:
      name: assigned
      nav_header: "Project Assignment"
    edit:
      name: edit
  new_user:

plugin:
  index:
    clone:
      name: clone
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: trash
      path: ""
  not_index:
    assigned:
      name: assigned
      nav_header: "Plugin Assignment"
    edit:
      name: edit
  new_user:

team:
  index:
    clone:
      name: clone
      nav_header: "Bulk Action"
      path: ""
    lock:
      name: lock
      path: ""
    trash:
      name: trash
      path: ""
  not_index:
    show:
      name: show
      nav_header: "View Action"
    edit:
      name: edit
    privileges:
      name: privileges
    perferences:
      name: perferences
  new_user:

setting:
  index:
    clone:
      name: clone
      nav_header: "Bulk Action"
      path: ""
    lock:
      name: lock
      path: ""
    trash:
      name: trash
      path: ""
  not_index:
    show:
      name: show
      nav_header: "View Action"
    edit:
      name: edit
    privileges:
      name: privileges
    perferences:
      name: perferences
  new_user:
