app:
  app_name: LavaStudio
  core_name: Magma
  app_version: 1.0.0
  core_version: 1.0.0
  app_email: magmacore@lavastudio.co.uk
  app_author: Ricardo Miller

settings:
  default_charset: UTF-8
  default_locale: en
  default_timezone: Europe/London
  favicon: ""
  apple_icon: ""
  secret_key: ""
  googleAnalytics: UA-XXXXX-Y

system:
  use_resolvable_action: false
  use_session: true
  use_cookie: true
  logger:
    use_logger: true
    log:
      - warnings
      - errors
      - critical
      - exceptions
    log_path: /Storage/Logs/
  use_translations: true
  use_csrf: true
  use_honeypot: true
  use_hash_cost_factor: 10
  use_auto_password: false,
  use_auth: true
  activation_token_expiration: 3600
  default_status: "pending"

  super_role:
    props:
      { name: Super, id: 1, description: Roles which contains all priviledges }
  default_role:
    props:
      {
        name: Subscriber,
        id: 2,
        description: Role which allows basic user access,
      }

gravatar:
  rating: R
  size: 200
  default: mystery #monsterid, identicon, wavatar, blank, default, mystery

security:
  password_pattern: '(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}'
  url_pattern: "https?://.+"
  search_pattern: "[^'\x22]+"
  email_pattern: '[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$'
  tel_pattern: "[0-9]{3}-[0-9]{3}-[0-9]{4}"

database:
  default_driver: "mysql"
  drivers:
    mysql:
      class: \MagmaCore\DataObjectLayer\Drivers\MysqlDatabaseConnection
    pgsql:
      class: \MagmaCore\DataObjectLayer\Drivers\PgsqlDatabaseConnection
    sqlite:
      class: \MagmaCore\DataObjectLayer\Drivers\SqliteDatabaseConnection

# Application debugging. Set the production when the application is ready for production. This is an
# important step as not doing so will expose sensitive information to your frontend users.
debug_error:
  mode: dev

# Custom error handling Which displays a much more descriptive and friendly error within development
# environment. When set to production use the log_path to specify where the exceptions should be
# logged. for later use
error_handler:
  error: \MagmaCore\ErrorHandler\ErrorHandler::errorHandle
  exception: \MagmaCore\ErrorHandler\ErrorHandler::exceptionHandle
  log_path: ""

logger_handler:
  file: \MagmaCore\Logger\Handler\NativeLoggerHandler
  array: \MagmaCore\Logger\Handler\ArrayLoggerHandler
  database: \MagmaCore\Logger\Handler\PdoLoggerHandler
  console: \MagmaCore\Logger\Handler\ConsoleLoggerHandler
  echo: \MagmaCore\Logger\Handler\EchoLoggerHandler


# Disallowed controllers prevent the any controller in the array list from being inserted into the database
# this primarily governs the admin panel control menu. As not all controller class is suited to have a
# menu item. If you want a particular controller to not be accessible from the admin menu. You will need to
# list it in the array below
disallowed_controllers:
  - home
  - security
  - password
  - activation
  - registration
  - profile
  - account
  - install
  - accessDenied
  - admin
  - event
  - notification
  - userRole