stylesheets:
  uikit:
    href: "https://cdn.jsdelivr.net/npm/uikit@3.6.5/dist/css/uikit.min.css"
    enable: true
    cdn: true
  ionicons:
    href: "https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"
    enable: true
    cdn: true
  google_pre_connect:
    href: "https://fonts.gstatic.com"
    enable: true
    cdn: true
  googleapis:
    href: "https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@200;300&display=swap"
    enable: true
    cdn: true
  notyf:
    href: "/public/assets/css/uikit/notyf.min.css"
    enable: true
    cdn: false
  custom:
    href: "/public/assets/css/uikit/custom.css"
    enable: true
    cdn: false

scripts:
  jquery:
    src: "https://code.jquery.com/jquery-3.4.1.min.js"
    integrity: "sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
    crossorigin: anonymous
    location: footer
    enable: true
    cdn: true
  fontawesome:
    src: "https://kit.fontawesome.com/b60c3fbedf.js"
    integrity: ""
    crossorigin: anonymous
    location: header
    enable: true
    cdn: true
  uikit:
    src: "https://cdn.jsdelivr.net/npm/uikit@3.4.2/dist/js/uikit.min.js"
    integrity: ""
    crossorigin: ""
    location: footer
    enable: true
    cdn: true
  uikit_icons:
    src: "https://cdn.jsdelivr.net/npm/uikit@3.4.2/dist/js/uikit-icons.min.js"
    integrity: ""
    crossorigin: ""
    location: footer
    enable: false
    cdn: true
  charts:
    src: "https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.min.js"
    integrity: "sha256-UGwvyUFH6Qqn0PSyQVw4q3vIX0wV1miKTracNJzAWPc="
    crossorigin: "anonymous"
    location: footer
    enable: false
    cdn: true
  jquery_transit:
    src: "https://cdnjs.cloudflare.com/ajax/libs/jquery.transit/0.9.12/jquery.transit.min.js"
    integrity: "sha256-rqEXy4JTnKZom8mLVQpvni3QHbynfjPmPxQVsPZgmJY="
    crossorigin: "anonymous"
    location: footer
    enable: true
    cdn: true
  notyf:
    src: "/public/assets/js/uikit/notyf.min.js"
    integrity: ""
    crossorigin: "anonymous"
    location: footer
    enable: true
    cdn: false
  sidebar:
    src: "/public/assets/js/uikit/sidebar.js"
    integrity: ""
    crossorigin: "anonymous"
    location: footer
    enable: true
    cdn: false
  ionicons:
    src: "https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"
    integrity: ""
    crossorigin: ""
    location: header
    enable: true
    cdn: true
  turbo_hotwire:
    src: "https://unpkg.com/@hotwired/turbo@7.0.0-beta.3/dist/turbo.es5-umd.js"
    integrity: ""
    crossorigin: ""
    location: header
    enable: true
    cdn: true
