stylesheets:
    uikit: 
        href: 'https://cdn.jsdelivr.net/npm/uikit@3.6.5/dist/css/uikit.min.css'
        enable: true
    ionicons: 
        href: 'https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css'
        enable: true
    googleapis: 
        href: 'https://fonts.googleapis.com/css?family=Lato|Nunito|Open+Sans+Condensed:300,700|Roboto|Oswald:wght@300&display=swap'
        enable: true

scripts:
    jquery:
        src: 'https://code.jquery.com/jquery-3.4.1.min.js'
        integrity: 'sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo='
        crossorigin: anonymous
        location: header
        enable: true
    fontawesome:
        src: 'https://kit.fontawesome.com/b60c3fbedf.js'
        integrity: ''
        crossorigin: anonymous
        location: header
        enable: true
    uikit:
        src: 'https://cdn.jsdelivr.net/npm/uikit@3.4.2/dist/js/uikit.min.js'
        integrity: ''
        crossorigin: ''
        location: footer
        enable: true
    uikit_icons:
        src: 'https://cdn.jsdelivr.net/npm/uikit@3.4.2/dist/js/uikit-icons.min.js'
        integrity: ''
        crossorigin: ''
        location: footer
        enable: true
    charts:
        src: 'https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.min.js'
        integrity: 'sha256-UGwvyUFH6Qqn0PSyQVw4q3vIX0wV1miKTracNJzAWPc='
        crossorigin: 'anonymous'
        location: footer
        enable: true
    jquery_transit:
        src: 'https://cdnjs.cloudflare.com/ajax/libs/jquery.transit/0.9.12/jquery.transit.min.js'
        integrity: 'sha256-rqEXy4JTnKZom8mLVQpvni3QHbynfjPmPxQVsPZgmJY='
        crossorigin: 'anonymous'
        location: footer
        enable: true
    vue_js:
        src: 'https://cdn.jsdelivr.net/npm/vue@2.6.11'
        integrity: ''
        crossorigin: ''
        location: footer
        enable: true
    axios_js:
        src: 'https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js'
        integrity: ''
        crossorigin: ''
        location: footer
        enable: true
  