user:
  index:
    copy:
      name: copy
      icon: copy-outline
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: delete
      path: ""
      icon: trash-outline
    export:
      name: export
      path: ""
      icon: download-outline
  not_index:
    show:
      name: show
      nav_header: "View Action"
    edit:
      name: edit
    privilege:
      name: privilege
    preferences:
      name: preferences

group:
  index:
    copy:
      name: copy
      icon: copy-outline
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: delete
      path: ""
      icon: trash-outline
  not_index:
    assigned:
      name: assigned
      nav_header: "Group Assignment"
    edit:
      name: edit

role:
  index:
    copy:
      name: copy
      icon: copy-outline
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: delete
      path: ""
      icon: trash-outline
  not_index:
    assigned:
      name: assigned
      nav_header: "Role Assignment"
    edit:
      name: edit

permission:
  index:
    copy:
      name: copy
      icon: copy-outline
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: delete
      path: ""
      icon: trash-outline
  not_index:
    assigned:
      name: assigned
      nav_header: "Permission Assignment"
    edit:
      name: edit
  new_user:

ticket:
  index:
    copy:
      name: copy
      icon: copy-outline
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: delete
      path: ""
      icon: trash-outline
  not_index:
    assigned:
      name: assigned
      nav_header: "Role Assignment"
    edit:
      name: edit


project:
  index:
    copy:
      name: copy
      icon: copy-outline
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: delete
      path: ""
      icon: trash-outline
  not_index:
    assigned:
      name: assigned
      nav_header: "Project Assignment"
    edit:
      name: edit
  new_user:

plugin:
  index:
    copy:
      name: copy
      icon: copy-outline
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: delete
      path: ""
      icon: trash-outline
  not_index:
    assigned:
      name: assigned
      nav_header: "Plugin Assignment"
    edit:
      name: edit
  new_user:

team:
  index:
    copy:
      name: copy
      icon: copy-outline
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: delete
      path: ""
      icon: trash-outline
  not_index:
    show:
      name: show
      nav_header: "View Action"
    edit:
      name: edit
    privileges:
      name: privilege
    perferences:
      name: perferences
  new_user:

setting:
  index:
    copy:
      name: copy
      icon: copy-outline
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: delete
      path: ""
      icon: trash-outline
  not_index:
    show:
      name: show
      nav_header: "View Action"
    edit:
      name: edit
    privileges:
      name: privilege
    perferences:
      name: perferences
  new_user:
accessDenied:
  index:
    copy:
      name: copy
      icon: copy-outline
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: delete
      path: ""
      icon: trash-outline
  not_index:
    show:
      name: show
      nav_header: "View Action"
    edit:
      name: edit
    privileges:
      name: privilege
    perferences:
      name: perferences
  new_user:
menu:
  index:
    copy:
      name: copy
      icon: copy-outline
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: delete
      path: ""
      icon: trash-outline
  not_index:
    show:
      name: show
      nav_header: "View Action"
    edit:
      name: edit
    privileges:
      name: privilege
    perferences:
      name: perferences
  new_user:

notification:
  index:
    copy:
      name: copy
      icon: copy-outline
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: delete
      path: ""
      icon: trash-outline
  not_index:
    show:
      name: show
      nav_header: "View Action"
    edit:
      name: edit
    privileges:
      name: privilege
    perferences:
      name: perferences
  new_user:

message:
  index:
    copy:
      name: copy
      icon: copy-outline
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: delete
      path: ""
      icon: trash-outline
  not_index:
    show:
      name: show
      nav_header: "View Action"
    edit:
      name: edit
    privileges:
      name: privilege
    perferences:
      name: perferences
  new_user:

system:
  index:
    copy:
      name: copy
      icon: copy-outline
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: delete
      path: ""
      icon: trash-outline
  not_index:
    show:
      name: show
      nav_header: "View Action"
    edit:
      name: edit
    privileges:
      name: privilege
    perferences:
      name: perferences
  new_user:

post:
  index:
    copy:
      name: copy
      icon: copy-outline
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: delete
      path: ""
      icon: trash-outline
  not_index:
    show:
      name: show
      nav_header: "View Action"
    edit:
      name: edit
    privileges:
      name: privilege
    perferences:
      name: perferences
  new_user:

category:
  index:
    copy:
      name: copy
      icon: copy-outline
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: delete
      path: ""
      icon: trash-outline
  not_index:
    show:
      name: show
      nav_header: "View Action"
    edit:
      name: edit
    privileges:
      name: privilege
    perferences:
      name: perferences
  new_user:

tag:
  index:
    copy:
      name: copy
      icon: copy-outline
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: delete
      path: ""
      icon: trash-outline
  not_index:
    show:
      name: show
      nav_header: "View Action"
    edit:
      name: edit
    privileges:
      name: privilege
    perferences:
      name: perferences
  new_user:

notification:
  index:
    copy:
      name: copy
      icon: copy-outline
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: delete
      path: ""
      icon: trash-outline
  not_index:
    show:
      name: show
      nav_header: "View Action"
    edit:
      name: edit
    privileges:
      name: privilege
    perferences:
      name: perferences
  new_user:

