user:
  index:
    log:
      name: log
      icon: file-edit
      nav_header: "Action"
      path: "/admin/user/log"
    setting:
      name: settings
      path: "/admin/user/settings"
      icon: cog
    export:
      name: export
      path: "/admin/user/export"
      icon: download-outline
    import:
      name: import
      path: "/admin/user/import"
      icon: upload-outline

  not_index:
    show:
      name: show
      nav_header: "View Action"
    edit:
      name: edit
    privilege:
      name: privilege
    preferences:
      name: preferences

leave:
  index:
    log:
      name: log
      icon: file-edit
      nav_header: "Action"
      path: "/admin/leave/log"
    setting:
      name: settings
      path: "/admin/leave/settings"
      icon: cog
    export:
      name: export
      path: "/admin/leave/export"
      icon: download-outline
    import:
      name: import
      path: "/admin/leave/import"
      icon: upload-outline
  not_index:
    assigned:
      name: assigned
      nav_header: "Group Assignment"
    edit:
      name: edit

holiday:
  index:
    log:
      name: log
      icon: file-edit
      nav_header: "Action"
      path: "/admin/holiday/log"
    setting:
      name: settings
      path: "/admin/holiday/settings"
      icon: cog
    export:
      name: export
      path: "/admin/holiday/export"
      icon: download-outline
    import:
      name: import
      path: "/admin/holiday/import"
      icon: upload-outline
  not_index:
    assigned:
      name: assigned
      nav_header: "Holiday Assignment"
    edit:
      name: edit


group:
  index:
    log:
      name: log
      icon: file-edit
      nav_header: "Action"
      path: "/admin/group/log"
    setting:
      name: settings
      path: "/admin/group/settings"
      icon: cog
    export:
      name: export
      path: "/admin/group/export"
      icon: download-outline
    import:
      name: import
      path: "/admin/group/import"
      icon: upload-outline
  not_index:
    assigned:
      name: assigned
      nav_header: "Group Assignment"
    edit:
      name: edit

role:
  index:
    log:
      name: log
      icon: file-edit
      nav_header: "Action"
      path: "/admin/role/log"
    setting:
      name: settings
      path: "/admin/role/settings"
      icon: cog
    export:
      name: export
      path: "/admin/role/export"
      icon: download-outline
    import:
      name: import
      path: "/admin/role/import"
      icon: upload-outline
  not_index:
    assigned:
      name: assigned
      nav_header: "Role Assignment"
    edit:
      name: edit

permission:
  index:
    log:
      name: log
      icon: file-edit
      nav_header: "Action"
      path: "/admin/permission/log"
    setting:
      name: settings
      path: "/admin/permission/settings"
      icon: cog
    export:
      name: export
      path: "/admin/permission/export"
      icon: download-outline
    import:
      name: import
      path: "/admin/permission/import"
      icon: upload-outline

  not_index:
    assigned:
      name: assigned
      nav_header: "Permission Assignment"
    edit:
      name: edit
  new_user:

ticket:
  index:
    log:
      name: log
      icon: file-edit
      nav_header: "Action"
      path: "/admin/ticket/log"
    setting:
      name: settings
      path: "/admin/ticket/settings"
      icon: cog
  not_index:
    assigned:
      name: assigned
      nav_header: "Role Assignment"
    edit:
      name: edit


project:
  index:
    copy:
      name: copy
      icon: copy-outline
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: delete
      path: ""
      icon: trash-outline
  not_index:
    assigned:
      name: assigned
      nav_header: "Project Assignment"
    edit:
      name: edit
  new_user:

plugin:
  index:
    copy:
      name: copy
      icon: copy-outline
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: delete
      path: ""
      icon: trash-outline
  not_index:
    assigned:
      name: assigned
      nav_header: "Plugin Assignment"
    edit:
      name: edit
  new_user:

team:
  index:
    copy:
      name: copy
      icon: copy-outline
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: delete
      path: ""
      icon: trash-outline
  not_index:
    show:
      name: show
      nav_header: "View Action"
    edit:
      name: edit
    privileges:
      name: privilege
    perferences:
      name: perferences
  new_user:

setting:
  index:
    copy:
      name: copy
      icon: copy-outline
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: delete
      path: ""
      icon: trash-outline
  not_index:
    show:
      name: show
      nav_header: "View Action"
    edit:
      name: edit
    privileges:
      name: privilege
    perferences:
      name: perferences
  new_user:
accessDenied:
  index:
    copy:
      name: copy
      icon: copy-outline
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: delete
      path: ""
      icon: trash-outline
  not_index:
    show:
      name: show
      nav_header: "View Action"
    edit:
      name: edit
    privileges:
      name: privilege
    perferences:
      name: perferences
  new_user:
menu:
  index:
    log:
      name: log
      icon: file-edit
      nav_header: "Action"
      path: "/admin/menu/log"
    setting:
      name: settings
      path: "/admin/menu/settings"
      icon: cog
  not_index:
    show:
      name: show
      nav_header: "View Action"
    edit:
      name: edit
    privileges:
      name: privilege
    perferences:
      name: perferences
  new_user:

notification:
  index:
    copy:
      name: copy
      icon: copy-outline
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: delete
      path: ""
      icon: trash-outline
  not_index:
    show:
      name: show
      nav_header: "View Action"
    edit:
      name: edit
    privileges:
      name: privilege
    perferences:
      name: perferences
  new_user:

message:
  index:
    log:
      name: log
      icon: file-edit
      nav_header: "Action"
      path: "/admin/message/log"
    setting:
      name: settings
      path: "/admin/message/settings"
      icon: cog
  not_index:
    show:
      name: show
      nav_header: "View Action"
    edit:
      name: edit
    privileges:
      name: privilege
    perferences:
      name: perferences
  new_user:

system:
  index:
    copy:
      name: copy
      icon: copy-outline
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: delete
      path: ""
      icon: trash-outline
  not_index:
    show:
      name: show
      nav_header: "View Action"
    edit:
      name: edit
    privileges:
      name: privilege
    perferences:
      name: perferences
  new_user:

post:
  index:
    log:
      name: log
      icon: file-edit
      nav_header: "Action"
      path: "/admin/post/log"
    setting:
      name: settings
      path: "/admin/post/settings"
      icon: cog
  not_index:
    show:
      name: show
      nav_header: "View Action"
    edit:
      name: edit
    privileges:
      name: privilege
    perferences:
      name: perferences
  new_user:

category:
  index:
    log:
      name: log
      icon: file-edit
      nav_header: "Action"
      path: "/admin/category/log"
    setting:
      name: settings
      path: "/admin/category/settings"
      icon: cog
    export:
      name: export
      path: "/admin/category/export"
      icon: download-outline
    import:
      name: import
      path: "/admin/category/import"
      icon: upload-outline
  not_index:
    show:
      name: show
      nav_header: "View Action"
    edit:
      name: edit
    privileges:
      name: privilege
    perferences:
      name: perferences
  new_user:

tag:
  index:
    log:
      name: log
      icon: file-edit
      nav_header: "Action"
      path: "/admin/tag/log"
    setting:
      name: settings
      path: "/admin/tag/settings"
      icon: cog
  not_index:
    show:
      name: show
      nav_header: "View Action"
    edit:
      name: edit
    privileges:
      name: privilege
    perferences:
      name: perferences
  new_user:

discovery:
  index:
    copy:
      name: copy
      icon: copy-outline
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: delete
      path: ""
      icon: trash-outline
  not_index:
    show:
      name: show
      nav_header: "View Action"
    edit:
      name: edit
    privileges:
      name: privilege
    perferences:
      name: perferences
  new_user:

history:
  index:
    copy:
      name: copy
      icon: copy-outline
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: delete
      path: ""
      icon: trash-outline
  not_index:
    show:
      name: show
      nav_header: "View Action"
    edit:
      name: edit
    privileges:
      name: privilege
    perferences:
      name: perferences
  new_user:

support:
  index:
    copy:
      name: copy
      icon: copy-outline
      nav_header: "Bulk Action"
      path: ""
    trash:
      name: delete
      path: ""
      icon: trash-outline
  not_index:
    show:
      name: show
      nav_header: "View Action"
    edit:
      name: edit
    privileges:
      name: privilege
    perferences:
      name: perferences
  new_user:

