user:
    additional_conditions: []
    selectors: []
    records_per_page: 5
    query: status
    filter_by: ['lastname']
    filter_alias: s                     ## associated to html form input name attribute
    sort_columns:                       ## Specifies an array of columns we can sort table by
        - firstname
        - created_at
        - modified_at
role:
    additional_conditions: []
    selectors: []
    records_per_page: 5
    query: ''
    filter_by: ['role_name']
    filter_alias: s
    sort_columns:
        - role_name
        - created_at
        - modified_at

role_perm:
    additional_conditions: []
    selectors: []
    records_per_page: 5
    query: ''
    filter_by: ['permission_name']
    filter_alias: s
    sort_columns:
        - role_id
        
permission:
    additional_conditions: []
    selectors: []
    records_per_page: 5
    query: ''
    filter_by: ['permission_name']
    filter_alias: s
    sort_columns:
        - permission_name
        - created_at
        - modified_at
                
post:
    additional_conditions: []
    selectors: []
    records_per_page: 30
    query: ''
    filter_by: ['title']
    filter_alias: s
    sort_columns:
        - title
        - created_at
        - modified_at

tag:
    additional_conditions: []
    selectors: []
    records_per_page: 10
    query: ''
    filter_by: ['tag_name']
    filter_alias: s
    sort_columns:
        - tag_name
        - created_at
        - modified_at
category:
    additional_conditions: []
    selectors: []
    records_per_page: 10
    query: ''
    filter_by: ['cat_name']
    filter_alias: s
    sort_columns:
        - cat_name
        - created_at
        - modified_at
