services: 
    subscribers:
        user.subscriber:
            class: \App\EventSubscriber\UserActionSubscriber
            props:
                - {}
        role.subscriber:
            class: \App\EventSubscriber\RoleActionSubscriber
            props: 
                - {}
    listeners:
        my.listener1:
            class: \App\EventListener\RoleListener
            props:
                - { name: 'app.event.listener.role_listener', event: doUpdate }