services: 
    subscribers:
        user.subscriber:
            class: \App\EventSubscriber\UserActionSubscriber
            props:
                - {}
            register_route_feedback:
                \App\Controller\Admin\UserController:
                    newAction: 
                        - { msg: New user added!}
                    editAction: 
                        - { msg: Changes saved!}
                    deleteAction: 
                        - { msg: User deleted successfully! }
                
        role.subscriber:
            class: \App\EventSubscriber\RoleActionSubscriber
            props: 
                - {}
        permission.subscriber:
            class: \App\EventSubscriber\PermissionActionSubscriber
            props: 
                - {}
        login.subscriber:
            class: \App\EventSubscriber\LoginActionSubscriber
            props: 
                - {}
        password.subscriber:
            class: \App\EventSubscriber\PasswordActionSubscriber
            props: 
                - {}
        activate.subscriber:
            class: \App\EventSubscriber\ActivateActionSubscriber
            props: 
                - {}
    listeners:
        my.listener1:
            class: \App\EventListener\RoleListener
            props:
                - { name: 'app.event.listener.role_listener', event: doUpdate }