services:
  subscribers:
    user.subscriber:
      class: \App\EventSubscriber\UserActionSubscriber
      props:
        - {}
      register_route_feedback:
        App\Controller\Admin\UserController::newAction:
          msg: New user added!
        App\Controller\Admin\UserController::editAction:
          msg: Changes saved!
        App\Controller\Admin\UserController::deleteAction:
          msg: User deleted successfully!
        App\Controller\RegistrationController::registerAction:
          msg: Your account was created!

    account.subscriber:
      class: \App\EventSubscriber\UserActionSubscriber
      props:
        - {}
      register_route_feedback:
        App\Controller\Profile\AccountController::nameAction:
          msg: You've successfully updated your name!
        App\Controller\Profile\AccountController::emailAction:
          msg: You've successfully updated your email address!
        App\Controller\Profile\AccountController::passwordAction:
          msg: You've successfully updated your password!

    role.subscriber:
      class: \App\EventSubscriber\RoleActionSubscriber
      props:
        - {}
      register_route_feedback:
        App\Controller\Admin\RoleController::newAction:
          msg: New Role Added!
        App\Controller\Admin\RoleController::editAction:
          msg: Role updated!
        App\Controller\Admin\RoleController::deleteAction:
          msg: Role Deleted!

    permission.subscriber:
      class: \App\EventSubscriber\PermissionActionSubscriber
      props:
        - {}
      register_route_feedback:
        App\Controller\Admin\PermissionController::newAction:
          msg: New permission added!
        App\Controller\Admin\PermissionController::editAction:
          msg: Permission updated!
        App\Controller\Admin\PermissionController::deleteAction:
          msg: Permission deleted!

    security.subscriber:
      class: \App\EventSubscriber\LoginActionSubscriber
      props:
        - {}
      register_route_feedback:
        App\Controller\SecurityController::indexAction:
          msg: Welcome back!
        App\Controller\SecurityController::logoutAction:
          msg: You've successfully logged out!

    password.subscriber:
      class: \App\EventSubscriber\PasswordActionSubscriber
      props:
        - {}
    activate.subscriber:
      class: \App\EventSubscriber\ActivateActionSubscriber
      props:
        - {}
  listeners:
    my.listener1:
      class: \App\EventListener\RoleListener
      props:
        - { name: "app.event.listener.role_listener", event: doUpdate }
