services:
  subscribers:
#    base_controller.subscriber:
#      class: \MagmaCore\Base\EventSubscriber\BaseControllerActionSubscriber
#      props:
#        - {}

    user.subscriber:
      class: \App\EventSubscriber\UserActionSubscriber
      props:
        - {}
      register_route_feedback:
        App\Controller\Admin\UserController::newAction:
          msg: New user added!
        App\Controller\Admin\UserController::editAction:
          msg: Changes saved!
        App\Controller\Admin\UserController::deleteAction:
          msg: User deleted successfully!
        App\Controller\Admin\UserController::bulkAction:
          msg: Bulk action successful!
        App\Controller\RegistrationController::registerAction:
          msg: Your account was created!
        App\Controller\RegistrationController::trashAction:
          msg: Account is in located within the trash!
        App\Controller\RegistrationController::trashRestoreAction:
          msg: Account restored from trash!

    role.subscriber:
      class: \App\EventSubscriber\RoleActionSubscriber
      props:
        - {}
      register_route_feedback:
        App\Controller\Admin\RoleController::newAction:
          msg: New Role Added!
        App\Controller\Admin\RoleController::editAction:
          msg: Role updated!
        App\Controller\Admin\RoleController::deleteAction:
          msg: Role Deleted!

    permission.subscriber:
      class: \App\EventSubscriber\PermissionActionSubscriber
      props:
        - {}
      register_route_feedback:
        App\Controller\Admin\PermissionController::newAction:
          msg: New permission added!
        App\Controller\Admin\PermissionController::editAction:
          msg: Permission updated!
        App\Controller\Admin\PermissionController::deleteAction:
          msg: Permission deleted!

    userRole.subscriber:
      class: \App\EventSubscriber\UserRoleActionSubscriber
      props:
        - {}

    security.subscriber:
      class: \App\EventSubscriber\LoginActionSubscriber
      props:
        - {}
      register_route_feedback:
        App\Controller\SecurityController::indexAction:
          msg: Welcome back!
        App\Controller\SecurityController::logoutAction:
          msg: You've successfully logged out!

    security_logout.subscriber:
      class: \App\EventSubscriber\LogoutActionSubscriber
      props:
        - {}
      register_route_feedback:
        App\Controller\SecurityController::logoutAction:
          msg: You've successfully logged out!


    password.subscriber:
      class: \App\EventSubscriber\PasswordActionSubscriber
      props:
        - {}
      register_route_feedback:
        App\Controller\PasswordController::forgotAction:
          msg: Your request was successful. Please check your email address for reset link!
        App\Controller\PasswordController::resetAction:
          msg: Password reset successfully.

    activation.subscriber:
      class: \App\EventSubscriber\ActivateActionSubscriber
      props:
        - {}
      register_route_feedback:
        App\Controller\ActivateController::activateAction:
          msg: You're now activated

    controllerSettings.subscriber:
      class: \App\EventSubscriber\ControllerSettingsActionSubscriber
      props:
        - {}
      register_route_feedback:
        App\Controller\UserController::settingsAction:
          msg: Changes Saved

    registration.subscriber:
      class: \App\EventSubscriber\RegistrationActionSubscriber
      props:
        - {}
      register_route_feedback:
        App\Controller\RegistrationController::registerAction:
          msg: You're now registered
          redirect: /registration/registered
          
    setting.subscriber:
      class: \App\EventSubscriber\SettingActionSubscriber
      props:
        - {}
      register_route_feedback:
        App\Controller\Admin\SettingController::indexAction:
          msg: Changes Saved

    project.subscriber:
      class: \App\EventSubscriber\ProjectActionSubscriber
      props:
        - {}
      register_route_feedback:
        App\Controller\Admin\ProjectActionSubscriber::indexAction:
          msg: Changes Saved

    role_permission_assigned.subscriber:
      class: \App\EventSubscriber\RolePermissionAssignedActionSubscriber
      props:
        - {}
      register_route_feedback:
        App\Controller\Admin\RoleController::assignedAction:
          msg: Changes Saved

#  listeners:
#    inertia.listener:
#      class: \MagmaCore\Inertia\InertiaListener
#      props:
#        - { name: "app.event.listener.send_registration_email_listener", event: '' }
