services:
  subscribers:
    project.subscriber:
      class: \App\EventSubscriber\ProjectActionSubscriber
      register_route_feedback:
        App\Controller\Admin\ProjectActionSubscriber::indexAction:
          msg: Changes Saved

    category.subscriber:
      class: \App\EventSubscriber\CategoryActionSubscriber
      register_route_feedback:
        App\Controller\Admin\CategoryController::newAction:
          msg: New category added successfully!
          redirect: category.new
        App\Controller\Admin\CategoryController::editAction:
          msg: Changes saved!
        App\Controller\Admin\CategoryController::trashAction:
          msg: Item thrown in the trash!
        App\Controller\Admin\CategoryController::untrashAction:
          msg: Category restored from trash!
          redirect: category.index
        App\Controller\Admin\CategoryController::hardDeleteAction:
          msg: Category permanently deleted!
          redirect: category.index

    tag.subscriber:
      class: \App\EventSubscriber\TagActionSubscriber
      register_route_feedback:
        App\Controller\Admin\TagController::newAction:
          msg: New tag added successfully!
        App\Controller\Admin\TagController::editAction:
          msg: Changes saved!
        App\Controller\Admin\TagController::trashAction:
          msg: Item thrown in the trash!
          redirect: tag.index
        App\Controller\Admin\TagController::untrashAction:
          msg: Tag restored from trash!
          redirect: tag.index
        App\Controller\Admin\TagController::hardDeleteAction:
          msg: Tag permanently deleted!
          redirect: tag.index

    post.subscriber:
      class: \App\EventSubscriber\PostActionSubscriber
      register_route_feedback:
        App\Controller\Admin\PostController::newAction:
          msg: New post added successfully!
        App\Controller\Admin\PostController::editAction:
          msg: Changes saved!
        App\Controller\Admin\PostController::trashAction:
          msg: Item thrown in the trash!
          redirect: post.index
        App\Controller\Admin\PostController::untrashAction:
          msg: Post restored from trash!
          redirect: post.index
        App\Controller\Admin\PostController::hardDeleteAction:
          msg: Post permanently deleted!
          redirect: post.index
