dashboard:
  name: Dashboard
  icon: bi bi-speedometer2
  path: /admin/dashboard/index
  roles: {}
  header: Manager
authentication:
  title: Manage User
  name: Users
  icon: bi bi-person-fill
  path: ""
  children:
    users:
      name: Users
      icon: ''
      path: "/admin/user/index"
      role:
        - developer
    role:
      name: Roles
      icon: ''
      path: "/admin/role/index"
      role:
        - developer
    permission:
      name: Permission
      icon: ''
      path: "/admin/permission/index"
      role:
        - developer
    log:
      name: Log
      icon: ''
      path: "/admin/log/index"
      role:
        - developer
    setting:
      name: Settings
      icon: ''
      path: "/admin/log/index"
      role:
        - developer
