dashboard:
  name: Dashboard
  icon: speedometer-outline
  path: /admin/dashboard/index
  roles: {}
 
authentication:
  title: Manage User
  name: Users
  icon: person-outline
  path: ""
  header: Manager
  children:
    users:
      name: Users
      icon: ''
      path: "/admin/user/index"
      role:
        - developer
    role:
      name: Roles
      icon: ''
      path: "/admin/role/index"
      role:
        - developer
    permission:
      name: Permission
      icon: ''
      path: "/admin/permission/index"
      role:
        - developer

project:
  title: Project Manager
  name: Projects
  icon: person-outline
  path: ""
  children:
    projects:
      name: Projects
      icon: ''
      path: "/admin/project/index"
    new:
      name: New
      icon: ''
      path: "/admin/project/new"
    show:
      name: View
      icon: ''
      path: "/admin/project/show"
    log:
      name: Log
      icon: ''
      path: "/admin/project/log"

settings:
  title: Settings
  name: Settings
  icon: settings-outline
  path: "/admin/setting/index"
  header: Tools
plugins:
  title: Plugins
  name: Plugins
  icon: extension-puzzle-outline
  path: /admin/plugin/index
