dashboard:
    name: Dashboard
    icon: home
    path: /admin/dashboard/index
    roles: {}
    header: Manager
authentication:
    name: Users
    icon: user
    path: ''
    children:
        users:
            name: Users
            icon: users
            path: '[%user_edit%]'
            role:
                - developer
