dashboard:
  name: Dashboard
  icon: speedometer-outline
  path: /admin/dashboard/index
  rule: can_view
 
authentication:
  title: Manage User
  name: Users
  icon: person-outline
  path: ""
  header: Manager
  children:
    users:
      name: View All
      icon: ''
      path: "/admin/user/index"
      rule: can_view
    new:
      name: Add New
      path: '/admin/user/new'
      rule: can_add
    log:
      name: Logs
      path: '/admin/user/log'
      rule: can_log
    stats:
      name: Statistics
      path: ''
      rule: can_view_statistics
    role:
      name: Roles
      path: '/admin/role/index'
      rule: can_view
    permissions:
      name: Permissions
      path: '/admin/permission/index'
      rule: can_view
role:
  name: Role
  icon: ''
  path: '/admin/role/index'
  children:
    view:
      name: View All
      path: '/admin/role/index'
    new:
      name: Add New
      path: '/admin/role/new'
    log:
      name: Logs
      path: ''

permission:
  name: Permission
  icon: ''
  path: /admin/permission/index
  children:
    view:
      name: View All
      path: '/admin/permission/index'
    new:
      name: Add New
      path: '/admin/permission/new'
    log:
      name: Logs
      path: ''


#project:
#  title: Project Manager
#  name: Projects
#  icon: person-outline
#  path: ""
#  children:
#    projects:
#      name: View All
#      icon: ''
#      path: "/admin/project/index"
#    new:
#      name: Add New
#      icon: ''
#      path: "/admin/project/new"
#    log:
#      name: Log
#      icon: ''
#      path: "/admin/project/log"
#    stats:
#      name: Statistics
#      path: ''
#
settings:
  title: Settings
  name: Settings
  icon: settings-outline
  path: "/admin/setting/index"
  header: Tools
menu:
  title: Menu
  name: Menu
  icon: extension-puzzle-outline
  path: /admin/menu/index

plugins:
  title: Plugins
  name: Plugins
  icon: extension-puzzle-outline
  path: /admin/plugin/index
