dashboard:
  name: Dashboard
  icon: ion-speedometer
  path: /admin/dashboard/index
  roles: {}
  header: Manager
authentication:
  name: Users
  icon: ion-person
  path: ""
  children:
    users:
      name: Users
      icon: ion-person-stalker
      path: "/admin/user/index"
      role:
        - developer
    role:
      name: Roles
      icon: ion-locked
      path: "/admin/role/index"
      role:
        - developer
    permission:
      name: Permission
      icon: ion-key
      path: "/admin/permission/index"
      role:
        - developer
    log:
      name: Log
      icon: ion-compose
      path: "/admin/log/index"
      role:
        - developer
roles:
  name: Contacts
  icon: ion-clipboard
  path: "/admin/contact/index"
