index:
  clone:
    name: clone
    nav_header: "Bulk Action"
    path: ""
  trash:
    name: trash
    path: ""
not_index:
  assigned:
    name: assigned
    nav_header: "Permission Assignment"
  edit:
    name: edit
new_user:
  role_perm_title: Permissions
  role_perm_description: Choose a default role group for this user. Role group are roles with 1 or more permissions assigned. Only roles with permission are available here. If you choose no role by default the user will be assigned a subscriber role. Which only give read access.
