request:
  \MagmaCore\Http\RequestHandler
response:
  \MagmaCore\Http\ResponseHandler
formBuilder:
  \MagmaCore\FormBuilder\FormBuilder
eventDispatcher:
  \MagmaCore\EventDispatcher\EventDispatcher
error:
  \MagmaCore\Error\Error
tableGrid:
  \MagmaCore\Datatable\Datatable
collection:
  \MagmaCore\Collection\Collection
global:
  \MagmaCore\Session\GlobalManager\GlobalManager
flatDb:
  \MagmaCore\DataObjectLayer\FileStorageRepository\FileStorage
controllerSettingsModel:
  \App\Model\ControllerSettingsModel