# config/services.yaml
subscribers:
    flash_messages_subscriber:
        class: \App\EventSubscriber\FlashMessagesSubscriber
    new_user_subscriber:
        class: \App\EventSubscriber\NewUserSubscriber
    edit_user_subscriber:
        class: \App\EventSubscriber\EditUserSubscriber
    delete_user_subscriber:
        class: \App\EventSubscriber\DeleteUserSubscriber