# config/services.yaml
subscribers:
    App\EventListener\FlashMessagesSubscriber:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
            - { name: kernel.event_listener, event: kernel.exception }
