index:
  clone:
    name: clone
    nav_header: "Bulk Action"
    path: ""
  lock:
    name: lock
    path: ""
  trash:
    name: trash
    path: ""
not_index:
  show:
    name: show
    nav_header: "View Action"
  edit:
    name: edit
  privileges:
    name: privileges
  preferences:
    name: preferences
new_user:
  role_perm_title: Role and Permissions
  role_perm_description: Choose a default role group for this user. Role group are roles with 1 or more permissions assigned. Only roles with permission are available here. If you choose no role by default the user will be assigned a subscriber role. Which only give read access.
